apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "ex280-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "500m"
        memory: "300Mi"
      min:
        cpu: "10m"
        memory: "5Mi"
    - type: "Container"
      max:
        cpu: "500m"
        memory: "300Mi"
      min:
        cpu: "10m"
        memory: "5Mi"
      defaultRequest:
        cpu: "100m"
        memory: "100Mi"